[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/payment/:splat"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/payment/webhook"
  status = 200

# Redirect per SPA: tutte le route non trovate vanno a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Header per consentire l'uso di Google Translate e Firebase
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' translate.google.com translate.googleapis.com; style-src 'self' 'unsafe-inline' translate.googleapis.com fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: translate.google.com translate.googleapis.com; connect-src 'self' translate.googleapis.com *.firebaseio.com firestore.googleapis.com *.googleapis.com; frame-src translate.google.com" 