[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirezione principale per le API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/payment/:splat"
  status = 200
  force = true

# Redirects specifici per endpoint comuni
[[redirects]]
  from = "/api/create"
  to = "/.netlify/functions/payment/create"
  status = 200
  force = true

[[redirects]]
  from = "/api/status/*"
  to = "/.netlify/functions/payment/status/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/payment/health"
  status = 200
  force = true

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/payment/webhook"
  status = 200
  force = true

# Redirect per SPA: tutte le route non trovate vanno a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"
  NPM_FLAGS = "--no-audit --no-fund"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Header per consentire l'uso di Google Translate, Firebase e Stripe
[[headers]]
  for = "/*"
  [headers.values]
    # Aggiornata per essere più permissiva con Google Translate e prevenire problemi comuni
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' translate.google.com *.google.com *.googleapis.com *.gstatic.com *.stripe.com; style-src 'self' 'unsafe-inline' translate.googleapis.com fonts.googleapis.com *.google.com; font-src 'self' fonts.gstatic.com *.gstatic.com; img-src 'self' data: translate.google.com translate.googleapis.com *.google.com *.gstatic.com; connect-src 'self' translate.googleapis.com *.firebaseio.com firestore.googleapis.com *.googleapis.com *.stripe.com api.stripe.com www.google-analytics.com; frame-src 'self' translate.google.com *.google.com *.stripe.com; object-src 'none';" 